### ISSUE TITLE
quickstart

### ISSUE THREAD

**Issue by arademaker** [yandex/dep_tregex#1]
In the page https://yandex.github.io/dep_tregex/quickstart.html we don't have the link to download the zip. If I clone the repo and move to its root:

```
$ python2.6 -m'dep_tregex' html < ann.conllu
/usr/bin/python2.6: dep_tregex is a package and cannot be directly executed
```

How to execute it from the repo folder?

**Comment by dvorkanton** [comment]
Hello Alexandre!
The reason it doesn't work is that you are using python2.6. You can refer to http://stackoverflow.com/a/6630931/3601199, the ability to run a package was added in python2.7.
With python2.6, you have to specify main module manually:

`$ python2.6 -m'dep_tregex.__main__' html < ann.conllu`

Thank you for your comment, I'll try to fix the quickstart documentation based on it.

**Comment by dvorkanton** [comment]
Fixed: e6484241b468ba0ce93d4febf182ca47b61f9763

**Comment by arademaker** [comment]
thanks. But I still getting errors. With python 2.7

```
$ easy_install-2.7 ply
Searching for ply
Best match: ply 3.10
Processing ply-3.10-py2.7.egg
ply 3.10 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/site-packages/ply-3.10-py2.7.egg
Processing dependencies for ply
Finished processing dependencies for ply
urca:dep_tregex arademaker$ python2.7 -m'dep_tregex'
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "dep_tregex/__init__.py", line 5, in <module>
    from dep_tregex.tree_script import *
  File "dep_tregex/tree_script.py", line 3, in <module>
    import ply.lex
ImportError: No module named ply.lex
```

Idea?
